services:
  - type: web
    name: airbnb-backend
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    rootDir: .
    envVars:
      - key: DATABASE_URL
        value: mongodb+srv://phuongbt3232:5nKRvUps4ncQwKlD@cluster0.0y674.mongodb.net/test

