services:
  - type: web
    name: express-backend
    env: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
